import { getAutoGeneratedPlayList, getPublicPlayList, getPublicProfile, getPublicUploads, getRecommendedByProfile, getUploads, updateFollower } from "#/controllers/profile";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";

const router = Router();

router.post("/update-follower/:profiledId", mustAuth, updateFollower);
router.get("/uploads", mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playList/:profileId", getPublicPlayList);
router.get("/recommended", isAuth,  getRecommendedByProfile);
router.get("/auto-generated-palyList", mustAuth, getAutoGeneratedPlayList);



export default router;
