import { getAutoGeneratedPlayList, getFollowersProfile, getFollowersProfilePublic, getFollowingsProfile, getIsFollowing, getPlayListAudio, getPrivatePlayListAudio, getPublicPlayList, getPublicProfile, getPublicUploads, getRecommendedByProfile, getUploads, updateFollower } from "#/controllers/profile";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";

const router = Router();

router.post("/update-follower/:profiledId", mustAuth, updateFollower);
router.get("/uploads", mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playList/:profileId", getPublicPlayList);
router.get("/recommended", isAuth,  getRecommendedByProfile);
router.get("/auto-generated-palyList", mustAuth, getAutoGeneratedPlayList);
router.get("/followers", mustAuth, getFollowersProfile);
router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic);
router.get("/followings", mustAuth, getFollowingsProfile);
router.get("/playList-audios/:playListId", getPlayListAudio);
router.get("/private-palyList-audios/:playListId", mustAuth, getPrivatePlayListAudio);
router.get("/is-following/:profileId", getIsFollowing);


export default router;
